version: 2.1

workflows:
  run-all-tests:
    jobs:
      - run-chrome-tests:
          context: messenger-end-to-end

jobs:
  run-chrome-tests:
    docker:
      - image: atlassianlabs/docker-node-jdk-chrome-firefox
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: "Check context env"
          command: |
            echo $TEST_VAR1
            echo $TEST_VAR2
      - run:
          command: |
            npm install
            npm i cross-env -g
            npm install -g allure-commandline
            npm run tests
          environment:
            BROWSER_NAME: Chrome
            TESTRAIL_RUN: true
            ENABLE_SLACK: false
            TEST_VAR1: $TEST_VAR1
            ## LAMBDA_TEST_RUN: true
            ## JIRA_BASE_URL: $JIRA_BASE_URL
            ## JIRA_TOKEN: $JIRA_TOKEN
            ## JIRA_USER: $JIRA_USER
            ## LT_ACCESS_KEY: $LT_ACCESS_KEY
            ## LT_USERNAME: $LT_USERNAME
            ## SLACK_WEBHOOK: $SLACK_WEBHOOK
            ## TESTRAIL_BASE_URL: $TESTRAIL_BASE_URL
            ## TESTRAIL_PASSWORD: $TESTRAIL_PASSWORD
            ## TESTRAIL_USER: $TESTRAIL_USER
          name: "Run chrome tests"
      - store_artifacts:
          path: ~/project/artifacts