version: 2.0

jobs:
  run_chrome_tests:
    docker:
      - image: atlassianlabs/docker-node-jdk-chrome-firefox
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Run chrome tests
          command: |
            npm install
            npm i cross-env -g
            npm install -g allure-commandline
            npm run tests
          environment:
            # additional settings
            TESTRAIL_RUN: true
            LAMBDA_TEST_RUN: true
            ENABLE_SLACK: false

            # Chrome, IE, Safari
            BROWSER_NAME: Chrome

      - store_artifacts:
          path: ~/project/artifacts

workflows:
  version: 2
# need to add commands for other browsers
  run-all-tests:
    context: messengerEndToEnd
    jobs:
      - run_chrome_tests