version: 2.1

parameters:
  browser:
    type: string
    default: none # prevent running after pushing or merging. For running need to use api request with necessary parameters

workflows:
  version: 2
  run-all-tests:
    when:
      and:
        - equal: [ all, << pipeline.parameters.browser >> ]
    jobs:
      - run-chrome-tests:
          context: messenger-end-to-end
      - run-safari-tests:
          context: messenger-end-to-end
      - run-ie-tests:
          context: messenger-end-to-end

  run-only-chrome:
    when:
      and:
        - equal: [ chrome, << pipeline.parameters.browser >> ]
    jobs:
      - run-chrome-tests:
          context: messenger-end-to-end

  run-only-safari:
    when:
      and:
        - equal: [ safari, << pipeline.parameters.browser >> ]
    jobs:
      - run-safari-tests:
          context: messenger-end-to-end

  run-only-ie:
    when:
      and:
        - equal: [ ie, << pipeline.parameters.browser >> ]
    jobs:
      - run-ie-tests:
          context: messenger-end-to-end

jobs:
  run-chrome-tests:
    docker:
      - image: atlassianlabs/docker-node-jdk-chrome-firefox
    steps:
      - checkout
      - run:
          command: |
            npm install
            npm i cross-env -g
            npm install -g allure-commandline
            npm run tests
          environment:
            BROWSER_NAME: Chrome
          name: "Run chrome tests"
      - store_artifacts:
          path: ~/project/artifacts

  run-safari-tests:
    docker:
      - image: atlassianlabs/docker-node-jdk-chrome-firefox
    steps:
      - checkout
      - run:
          command: |
            npm install
            npm i cross-env -g
            npm install -g allure-commandline
            npm run tests
          environment:
            BROWSER_NAME: Safari
          name: "Run Safari tests"
      - store_artifacts:
          path: ~/project/artifacts

  run-ie-tests:
    docker:
      - image: atlassianlabs/docker-node-jdk-chrome-firefox
    steps:
      - checkout
      - run:
          command: |
            npm install
            npm i cross-env -g
            npm install -g allure-commandline
            npm run tests
          environment:
            BROWSER_NAME: IE
          name: "Run IE tests"
      - store_artifacts:
          path: ~/project/artifacts